// Generated by training/german_too.py from a German web crawl: dictionary words
// that are also ordinary German, where the language model may keep the original.
globalThis.HD_GERMAN_TOO = ["Bouillons", "Bub", "Buben", "Estrich", "Estriche", "Fahrausweis", "Gilets", "Gotte", "Kassier", "Konfitüre", "Konfitüren", "Kübel", "Lichtsignal", "Lichtsignalanlage", "Lichtsignalanlagen", "Lichtsignale", "Mami", "Mamis", "Match", "Matches", "Papis", "Parking", "Peperoni", "Pneus", "Pult", "Pulte", "Rande", "Store", "Sujet", "Untersuche"];
